# Generated by Django 6.0.1 on 2026-03-23 02:31

import applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('proposed_name_1', models.CharField(max_length=200)),
                ('proposed_name_2', models.CharField(blank=True, max_length=200)),
                ('nature_of_business', models.CharField(max_length=60)),
                ('business_type', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('lga', models.CharField(max_length=60)),
                ('business_address', models.CharField(max_length=255)),
                ('owner_first_name', models.CharField(max_length=60)),
                ('owner_last_name', models.CharField(max_length=60)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=30)),
                ('business_description', models.TextField(blank=True)),
                ('passport', models.ImageField(upload_to=applications.models.passport_upload_path)),
                ('signature', models.ImageField(upload_to=applications.models.signature_upload_path)),
                ('nin', models.FileField(upload_to=applications.models.nin_upload_path)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending Review'), ('queried', 'Queried'), ('approved', 'Approved')], default='submitted', max_length=20)),
                ('agent_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
