# Generated by Django 6.0.1 on 2026-04-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='previous_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
