# Generated by Django 6.0.1 on 2026-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_approved_at_application_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='registration_number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
