# Generated by Django 6.0.1 on 2026-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
