# Generated by Django 6.0.1 on 2026-04-05 13:51

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=applications.models.qr_upload_path),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
