# Generated by Django 6.0.1 on 2026-04-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_qr_code_application_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='digital_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
